package problem0002.solution1

/*
Problem statement from https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

// This calculates each number in the Fibonacci sequence, checks whether it is
// even, and if so, adds it to the sum.

fun main() {
    var prev = 1
    var cur = 2
    var evenSum = 0
    while (cur <= 4000000) {
        if (cur % 2 == 0) {
            evenSum += cur
        }
        val next = cur + prev
        prev = cur
        cur = next
    }
    println(evenSum)
}